name: deploy
on:
  push:
    branches:
      - 'dev'
    paths:
      - 'Prueba3/**'
jobs:
    paths:
    - '/PARTE3/**'
    deploy:
      name: deploy to cluster
      runs-on: latest
      steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository}}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha}}
